# Generated by Django 6.1 on 2026-08-27 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('tipo', models.CharField(choices=[('portal', 'Portal de convocatorias'), ('fundacion', 'Fundación / donante'), ('newsletter', 'Newsletter / boletín'), ('red', 'Red o alianza'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fuente',
                'verbose_name_plural': 'Fuentes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=255, verbose_name='Institución / Fuente')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha límite')),
                ('area', models.CharField(blank=True, max_length=255, verbose_name='Área temática')),
                ('monto', models.CharField(blank=True, max_length=120, verbose_name='Monto / Financiamiento')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('estado', models.CharField(choices=[('por_evaluar', 'Por evaluar'), ('pendiente', 'Pendiente'), ('en_preparacion', 'En preparación'), ('aplicada', 'Aplicada'), ('adjudicada', 'Adjudicada'), ('no_aplica', 'No aplica')], default='por_evaluar', max_length=20, verbose_name='Estado')),
                ('viabilidad', models.CharField(choices=[('por_evaluar', 'Por evaluar'), ('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='por_evaluar', max_length=20, verbose_name='Viabilidad según el perfil de nuestros proyectos')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convocatorias', to='convocatorias.fuente', verbose_name='Fuente relacionada')),
            ],
            options={
                'verbose_name': 'Convocatoria',
                'verbose_name_plural': 'Convocatorias',
                'ordering': ['fecha_limite'],
            },
        ),
    ]
