# Generated by Django 6.1 on 2026-08-31 18:39

import convocatorias.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del proyecto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='estado',
            field=models.CharField(choices=[('por_evaluar', 'Por evaluar'), ('pendiente', 'Pendiente'), ('en_preparacion', 'En preparación'), ('aplicada', 'Aplicada'), ('adjudicada', 'Adjudicada'), ('en_espera', 'En espera (cerrada / standby)'), ('no_aplica', 'No aplica')], default='por_evaluar', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=convocatorias.models.ruta_adjunto, verbose_name='Archivo')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('subido_en', models.DateTimeField(auto_now_add=True, verbose_name='Subido el')),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='convocatorias.convocatoria', verbose_name='Convocatoria')),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
                'ordering': ['-subido_en'],
            },
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='convocatorias', to='convocatorias.etiqueta', verbose_name='Etiquetas'),
        ),
        migrations.CreateModel(
            name='HistoricalConvocatoria',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('institucion', models.CharField(max_length=255, verbose_name='Institución / Fuente')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha límite')),
                ('area', models.CharField(blank=True, max_length=255, verbose_name='Área temática')),
                ('monto', models.CharField(blank=True, max_length=120, verbose_name='Monto / Financiamiento')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('estado', models.CharField(choices=[('por_evaluar', 'Por evaluar'), ('pendiente', 'Pendiente'), ('en_preparacion', 'En preparación'), ('aplicada', 'Aplicada'), ('adjudicada', 'Adjudicada'), ('en_espera', 'En espera (cerrada / standby)'), ('no_aplica', 'No aplica')], default='por_evaluar', max_length=20, verbose_name='Estado')),
                ('viabilidad', models.CharField(choices=[('por_evaluar', 'Por evaluar'), ('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='por_evaluar', max_length=20, verbose_name='Viabilidad según el perfil de nuestros proyectos')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado', models.DateTimeField(blank=True, editable=False)),
                ('actualizado', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fuente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='convocatorias.fuente', verbose_name='Fuente relacionada')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Convocatoria',
                'verbose_name_plural': 'historical Convocatorias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='proyectos',
            field=models.ManyToManyField(blank=True, related_name='convocatorias', to='convocatorias.proyecto', verbose_name='Proyectos relacionados'),
        ),
    ]
